import BookmarkConnector from '../connectors/system/BookmarkConnector.mjs'
import FolderConnector from '../connectors/system/FolderConnector.mjs'

import AnimExtremist from '../connectors/AnimExtremist.mjs'
/*
import * from '../connectors/11toon.mjs'
import * from '../connectors/8muses.mjs'
import * from '../connectors/9anime.mjs'
import * from '../connectors/9hentai.mjs'
import * from '../connectors/academyvn.mjs'
import * from '../connectors/actionmanga.mjs'
import * from '../connectors/ajianoscantrad.mjs'
import * from '../connectors/akaiyuhimun.mjs'
import * from '../connectors/allhentai.mjs'
import * from '../connectors/allmanga.mjs'
import * from '../connectors/anatanomotokare.mjs'
import * from '../connectors/animextremist.mjs'
import * from '../connectors/antisensescans.mjs'
import * from '../connectors/aoc.mjs'
import * from '../connectors/asmhentai.mjs'
import * from '../connectors/atelierdunoir.mjs'
import * from '../connectors/authrone.mjs'
import * from '../connectors/azoramanga.mjs'
import * from '../connectors/bacamanga.mjs'
import * from '../connectors/batoto.mjs'
import * from '../connectors/biamam.mjs'
import * from '../connectors/blogtruyen.mjs'
import * from '../connectors/booklive.mjs'
import * from '../connectors/boredomsociety.mjs'
import * from '../connectors/buka.mjs'
import * from '../connectors/bunnysscans.mjs'
import * from '../connectors/canismajorscans.mjs'
import * from '../connectors/centraldemangas.mjs'
import * from '../connectors/championscans.mjs'
import * from '../connectors/chibimanga.mjs'
import * from '../connectors/ciayoen.mjs'
import * from '../connectors/ciayoid.mjs'
import * from '../connectors/comicborder.mjs'
import * from '../connectors/comicdays.mjs'
import * from '../connectors/comicearthstar.mjs'
import * from '../connectors/comicextra.mjs'
import * from '../connectors/comicgardo.mjs'
import * from '../connectors/comicmeteor.mjs'
import * from '../connectors/comico.mjs'
import * from '../connectors/comicoid.mjs'
import * from '../connectors/comicvn.mjs'
import * from '../connectors/comicwalker.mjs'
import * from '../connectors/copypastescan.mjs'
import * from '../connectors/crunchymanga.mjs'
import * from '../connectors/dangolinenofansub.mjs'
import * from '../connectors/darkskyprojects.mjs'
import * from '../connectors/daumwebtoon.mjs'
import * from '../connectors/deathtollscans.mjs'
import * from '../connectors/desu.mjs'
import * from '../connectors/digitalteam.mjs'
import * from '../connectors/dokifansubs.mjs'
import * from '../connectors/dongmanmanhua.mjs'
import * from '../connectors/doujindesu.mjs'
import * from '../connectors/doujins.mjs'
import * from '../connectors/doujinyosh.mjs'
import * from '../connectors/dynasty-scans.mjs'
import * from '../connectors/egscans.mjs'
import * from '../connectors/ehentai.mjs'
import * from '../connectors/evilflowers.mjs'
import * from '../connectors/exhentai.mjs'
import * from '../connectors/eyeonmanga.mjs'
import * from '../connectors/fallenangelsscans.mjs'
import * from '../connectors/firstkiss.mjs'
import * from '../connectors/forgottenscans.mjs'
import * from '../connectors/fujoshibitches.mjs'
import * from '../connectors/funmanga.mjs'
import * from '../connectors/gammaplus.mjs'
import * from '../connectors/ganganonline.mjs'
import * from '../connectors/ganma.mjs'
import * from '../connectors/getmanhwa.mjs'
import * from '../connectors/gmanga.mjs'
import * from '../connectors/gntai.mjs'
import * from '../connectors/godsrealmscan.mjs'
import * from '../connectors/goldenmangas.mjs'
import * from '../connectors/grafimanga.mjs'
import * from '../connectors/hamtruyen.mjs'
import * from '../connectors/hanascan.mjs'
import * from '../connectors/happyteascans.mjs'
import * from '../connectors/hatigarmscans.mjs'
import * from '../connectors/heavenmanga.mjs'
import * from '../connectors/heavenmanga2.mjs'
import * from '../connectors/helveticascans.mjs'
import * from '../connectors/henchan.mjs'
import * from '../connectors/hentai2read.mjs'
import * from '../connectors/hentaicafe.mjs'
import * from '../connectors/hentaifox.mjs'
import * from '../connectors/hentaihere.mjs'
import * from '../connectors/hentainexus.mjs'
import * from '../connectors/hentairead.mjs'
import * from '../connectors/hitomi.mjs'
import * from '../connectors/hoducomics.mjs'
import * from '../connectors/holymanga.mjs'
import * from '../connectors/hoshikuzuuscans.mjs'
import * from '../connectors/hoshinofansub.mjs'
import * from '../connectors/hotchocolatescans.mjs'
import * from '../connectors/hunlightscans.mjs'
import * from '../connectors/hunterfansub.mjs'
import * from '../connectors/illuminatimanga.mjs'
import * from '../connectors/imangascans.mjs'
import * from '../connectors/imgur.mjs'
import * from '../connectors/inmanga.mjs'
import * from '../connectors/isekairaw.mjs'
import * from '../connectors/isekaiscan.mjs'
import * from '../connectors/iskultripscans.mjs'
import * from '../connectors/itascan.mjs'
import * from '../connectors/jaiminisbox.mjs'
import * from '../connectors/japanread.mjs'
import * from '../connectors/japscan.mjs'
import * from '../connectors/jokerfansub.mjs'
import * from '../connectors/justforfun.mjs'
import * from '../connectors/kaguyadex.mjs'
import * from '../connectors/kanjiku.mjs'
import * from '../connectors/kazemanga.mjs'
import * from '../connectors/kireicake.mjs'
import * from '../connectors/kirishimafansub.mjs'
import * from '../connectors/kiryuu.mjs'
import * from '../connectors/kissanime.mjs'
import * from '../connectors/kisscomic.mjs'
import * from '../connectors/kissdoujin.mjs'
import * from '../connectors/kissmanga-cdn.mjs'
import * from '../connectors/kissmanga.mjs'
import * from '../connectors/klikmanga.mjs'
import * from '../connectors/knightnofansub.mjs'
import * from '../connectors/kombatch.mjs'
import * from '../connectors/komikav.mjs'
import * from '../connectors/komikcast.mjs'
import * from '../connectors/komikgo.mjs'
import * from '../connectors/komikgue.mjs'
import * from '../connectors/komikid.mjs'
import * from '../connectors/komikindo.mjs'
import * from '../connectors/komikindoweb.mjs'
import * from '../connectors/komikmama.mjs'
import * from '../connectors/komikmanga.mjs'
import * from '../connectors/komikotaku.mjs'
import * from '../connectors/komikstation.mjs'
import * from '../connectors/komiku.mjs'
import * from '../connectors/komikzone.mjs'
import * from '../connectors/komiscans.mjs'
import * from '../connectors/kumanga.mjs'
import * from '../connectors/kuragebunch.mjs'
import * from '../connectors/kyuroku.mjs'
import * from '../connectors/leitor.mjs'
import * from '../connectors/lelscan.mjs'
import * from '../connectors/lelscanvf.mjs'
import * from '../connectors/leomanga.mjs'
import * from '../connectors/letitgoscans.mjs'
import * from '../connectors/leviatanscans-es.mjs'
import * from '../connectors/leviatanscans.mjs'
import * from '../connectors/lezhin-en.mjs'
import * from '../connectors/lezhin-ja.mjs'
import * from '../connectors/lezhin-ko.mjs'
import * from '../connectors/lhscan.mjs'
import * from '../connectors/lhtranslation.mjs'
import * from '../connectors/lilyreader.mjs'
import * from '../connectors/linewebtoon-en.mjs'
import * from '../connectors/linewebtoon-id.mjs'
import * from '../connectors/linewebtoon-th.mjs'
import * from '../connectors/linewebtoon-translate.mjs'
import * from '../connectors/linewebtoon-zh.mjs'
import * from '../connectors/lolivault.mjs'
import * from '../connectors/lupiteam.mjs'
import * from '../connectors/luscious.mjs'
import * from '../connectors/luxyscans.mjs'
import * from '../connectors/madokami.mjs'
import * from '../connectors/maid.mjs'
import * from '../connectors/manga-park.mjs'
import * from '../connectors/manga99.mjs'
import * from '../connectors/mangaarab.mjs'
import * from '../connectors/mangabat.mjs'
import * from '../connectors/mangacanblog.mjs'
import * from '../connectors/mangaceng.mjs'
import * from '../connectors/mangachan.mjs'
import * from '../connectors/mangacross.mjs'
import * from '../connectors/mangadeep.mjs'
import * from '../connectors/mangadenizi.mjs'
import * from '../connectors/mangadex.mjs'
import * from '../connectors/mangadoom.mjs'
import * from '../connectors/mangadoor.mjs'
import * from '../connectors/mangadropout-archive.mjs'
import * from '../connectors/mangadropout.mjs'
import * from '../connectors/mangaeden-en.mjs'
import * from '../connectors/mangaeden-it.mjs'
import * from '../connectors/mangaforall.mjs'
import * from '../connectors/mangafox.mjs'
import * from '../connectors/mangafoxfun.mjs'
import * from '../connectors/mangafreak.mjs'
import * from '../connectors/mangafull.mjs'
import * from '../connectors/mangago-cdn.mjs'
import * from '../connectors/mangago.mjs'
import * from '../connectors/mangahasu.mjs'
import * from '../connectors/mangahere.mjs'
import * from '../connectors/mangaherefun.mjs'
import * from '../connectors/mangahispano.mjs'
import * from '../connectors/mangahome.mjs'
import * from '../connectors/mangahost.mjs'
import * from '../connectors/mangahub.mjs'
import * from '../connectors/mangahubru.mjs'
import * from '../connectors/mangaichiscans.mjs'
import * from '../connectors/mangaid.mjs'
import * from '../connectors/mangaindo.mjs'
import * from '../connectors/mangaindoweb.mjs'
import * from '../connectors/mangainn.mjs'
import * from '../connectors/mangajinnofansub.mjs'
import * from '../connectors/mangakakalot.mjs'
import * from '../connectors/mangakakalotfun.mjs'
import * from '../connectors/mangakawaii.mjs'
import * from '../connectors/mangakid.mjs'
import * from '../connectors/mangakita.mjs'
import * from '../connectors/mangaku.mjs'
import * from '../connectors/mangalel.mjs'
import * from '../connectors/mangalib.mjs'
import * from '../connectors/mangalife.mjs'
import * from '../connectors/mangalike.mjs'
import * from '../connectors/mangalover-archive.mjs'
import * from '../connectors/mangalover.mjs'
import * from '../connectors/manganel.mjs'
import * from '../connectors/mangaoku.mjs'
import * from '../connectors/mangaonline.mjs'
import * from '../connectors/mangaonlinebr.mjs'
import * from '../connectors/mangapanda.mjs'
import * from '../connectors/mangapark-en.mjs'
import * from '../connectors/mangapark.mjs'
import * from '../connectors/mangapus.mjs'
import * from '../connectors/mangarawonline.mjs'
import * from '../connectors/mangareader.mjs'
import * from '../connectors/mangareadersite.mjs'
import * from '../connectors/mangarock.mjs'
import * from '../connectors/mangaroom.mjs'
import * from '../connectors/mangarussia.mjs'
import * from '../connectors/mangas.mjs'
import * from '../connectors/mangasail.mjs'
import * from '../connectors/mangascouts.mjs'
import * from '../connectors/mangasee.mjs'
import * from '../connectors/mangaseno.mjs'
import * from '../connectors/mangashiro.mjs'
import * from '../connectors/mangashow.mjs'
import * from '../connectors/mangastream.mjs'
import * from '../connectors/mangasubes.mjs'
import * from '../connectors/mangasushi.mjs'
import * from '../connectors/mangasy.mjs'
import * from '../connectors/mangatail.mjs'
import * from '../connectors/mangatellers.mjs'
import * from '../connectors/mangatensei.mjs'
import * from '../connectors/mangatoon-cn.mjs'
import * from '../connectors/mangatoon-en.mjs'
import * from '../connectors/mangatoon-es.mjs'
import * from '../connectors/mangatoon-id.mjs'
import * from '../connectors/mangatoon-vi.mjs'
import * from '../connectors/mangatown.mjs'
import * from '../connectors/mangatr.mjs'
import * from '../connectors/mangatube.mjs'
import * from '../connectors/mangavadisi.mjs'
import * from '../connectors/mangaweek.mjs'
import * from '../connectors/mangawindow.mjs'
import * from '../connectors/mangayosh.mjs'
import * from '../connectors/mangazuki-archive.mjs'
import * from '../connectors/mangazuki-club.mjs'
import * from '../connectors/mangazuki-info.mjs'
import * from '../connectors/mangazuki-online.mjs'
import * from '../connectors/mangazuki-raws.mjs'
import * from '../connectors/mangazuki-scans.mjs'
import * from '../connectors/mangazuki-site.mjs'
import * from '../connectors/mangazuki.mjs'
import * from '../connectors/manhuabox.mjs'
import * from '../connectors/manhuagui.mjs'
import * from '../connectors/manhuakan.mjs'
import * from '../connectors/manhuatai.mjs'
import * from '../connectors/manhwa18.mjs'
import * from '../connectors/manhwaclub.mjs'
import * from '../connectors/manhwahand.mjs'
import * from '../connectors/manhwahentai.mjs'
import * from '../connectors/manhwahentaime.mjs'
import * from '../connectors/manhwascan.mjs'
import * from '../connectors/manytoon.mjs'
import * from '../connectors/menudofansub.mjs'
import * from '../connectors/merakiscans.mjs'
import * from '../connectors/mexat.mjs'
import * from '../connectors/mintmanga.mjs'
import * from '../connectors/muchodoujins.mjs'
import * from '../connectors/muchohentai.mjs'
import * from '../connectors/myreadingmanga.mjs'
import * from '../connectors/naver.mjs'
import * from '../connectors/neoprojectscans.mjs'
import * from '../connectors/neteasecomic.mjs'
import * from '../connectors/nettruyen.mjs'
import * from '../connectors/neumanga.mjs'
import * from '../connectors/newtype.mjs'
import * from '../connectors/ngomik.mjs'
import * from '../connectors/nhentai.mjs'
import * from '../connectors/niadd.mjs'
import * from '../connectors/nightow.mjs'
import * from '../connectors/ninemanga-br.mjs'
import * from '../connectors/ninemanga-de.mjs'
import * from '../connectors/ninemanga-en.mjs'
import * from '../connectors/ninemanga-es.mjs'
import * from '../connectors/ninemanga-it.mjs'
import * from '../connectors/ninemanga-ru.mjs'
import * from '../connectors/ninjascans.mjs'
import * from '../connectors/noranofansub.mjs'
import * from '../connectors/ohtabooks.mjs'
import * from '../connectors/oneshotscans.mjs'
import * from '../connectors/onetimescans.mjs'
import * from '../connectors/onmanga.mjs'
import * from '../connectors/otakufile.mjs'
import * from '../connectors/otakuindo.mjs'
import * from '../connectors/patyscans.mjs'
import * from '../connectors/pcnet.mjs'
import * from '../connectors/pecintakomik.mjs'
import * from '../connectors/perveden-it.mjs'
import * from '../connectors/perveden.mjs'
import * from '../connectors/phoenixserenade.mjs'
import * from '../connectors/plottwistnofansub.mjs'
import * from '../connectors/pocketangelscans.mjs'
import * from '../connectors/porncomix.mjs'
import * from '../connectors/powermanga.mjs'
import * from '../connectors/psychoplay.mjs'
import * from '../connectors/pururin.mjs'
import * from '../connectors/puzzmos.mjs'
import * from '../connectors/pzykosis666hfansub.mjs'
import * from '../connectors/ravensscans-en.mjs'
import * from '../connectors/ravensscans-es.mjs'
import * from '../connectors/rawlh.mjs'
import * from '../connectors/rawmangasite.mjs'
import * from '../connectors/rawmangaupdate.mjs'
import * from '../connectors/rawqq.mjs'
import * from '../connectors/rawqv.mjs'
import * from '../connectors/rawsenmanga.mjs'
import * from '../connectors/readcomicbooksonline.mjs'
import * from '../connectors/readcomicsonline.mjs'
import * from '../connectors/readhentaimanga.mjs'
import * from '../connectors/readmanga.mjs'
import * from '../connectors/readmangaeu.mjs'
import * from '../connectors/readmanhua.mjs'
import * from '../connectors/readmng.mjs'
import * from '../connectors/readrawmanga.mjs'
import * from '../connectors/renascencescans.mjs'
import * from '../connectors/riceballicious.mjs'
import * from '../connectors/roseliascanlations.mjs'
import * from '../connectors/russification.mjs'
import * from '../connectors/s2scans.mjs'
import * from '../connectors/scanfr.mjs'
import * from '../connectors/scanmanga.mjs'
import * from '../connectors/scanop.mjs'
import * from '../connectors/scantrad.mjs'
import * from '../connectors/scantradunion.mjs'
import * from '../connectors/scanvf.mjs'
import * from '../connectors/seaotterscans.mjs'
import * from '../connectors/seinagiadultofansub.mjs'
import * from '../connectors/seinagifansub-en.mjs'
import * from '../connectors/seinagifansub-es.mjs'
import * from '../connectors/selfmanga.mjs'
import * from '../connectors/senmanga.mjs'
import * from '../connectors/sensescans.mjs'
import * from '../connectors/shakai.mjs'
import * from '../connectors/shogakukan.mjs'
import * from '../connectors/shonenjumpplus.mjs'
import * from '../connectors/shonenmagazine-pocket.mjs'
import * from '../connectors/shonenmagazine.mjs'
import * from '../connectors/shoujohearts.mjs'
import * from '../connectors/shoujosense.mjs'
import * from '../connectors/siberowl.mjs'
import * from '../connectors/silentskyscans.mjs'
import * from '../connectors/sixiangscans.mjs'
import * from '../connectors/sksubs.mjs'
import * from '../connectors/sleepypandascans.mjs'
import * from '../connectors/smackjeeves.mjs'
import * from '../connectors/solitarionofansub.mjs'
import * from '../connectors/somanga.mjs'
import * from '../connectors/sosscanlation.mjs'
import * from '../connectors/storminheaven.mjs'
import * from '../connectors/submanga.mjs'
import * from '../connectors/sundaywebry.mjs'
import * from '../connectors/taadd.mjs'
import * from '../connectors/tapas.mjs'
import * from '../connectors/taptrans.mjs'
import * from '../connectors/team1x1.mjs'
import * from '../connectors/tencentcomic.mjs'
import * from '../connectors/tenmanga.mjs'
import * from '../connectors/thecatscans.mjs'
import * from '../connectors/timelessleaf.mjs'
import * from '../connectors/tonarinoyoungjump.mjs'
import * from '../connectors/toomics-en.mjs'
import * from '../connectors/toomics-ko.mjs'
import * from '../connectors/toomics-sc.mjs'
import * from '../connectors/toomics-tc.mjs'
import * from '../connectors/toonily.mjs'
import * from '../connectors/toonkor.mjs'
import * from '../connectors/trashscanlations.mjs'
import * from '../connectors/tritiniascans.mjs'
import * from '../connectors/truecolorsscan.mjs'
import * from '../connectors/truyenchon.mjs'
import * from '../connectors/truyentranhtuan.mjs'
import * from '../connectors/tsubakinoscan.mjs'
import * from '../connectors/tsubasasociety.mjs'
import * from '../connectors/tsumino.mjs'
import * from '../connectors/tuhaomanhua.mjs'
import * from '../connectors/tumangaonline.mjs'
import * from '../connectors/tumangaonlinehentai.mjs'
import * from '../connectors/turkcraft.mjs'
import * from '../connectors/twistedhelscans.mjs'
import * from '../connectors/unionmangas.mjs'
import * from '../connectors/universoyuri.mjs'
import * from '../connectors/urasunday.mjs'
import * from '../connectors/valhallascans.mjs'
import * from '../connectors/vnsharing.mjs'
import * from '../connectors/vortexscans.mjs'
import * from '../connectors/vrv-crunchyroll.mjs'
import * from '../connectors/vrv-hidive.mjs'
import * from '../connectors/vrv-roosterteeth.mjs'
import * from '../connectors/webace.mjs'
import * from '../connectors/webcomicgamma.mjs'
import * from '../connectors/webcomicsapp.mjs'
import * from '../connectors/webnovel.mjs'
import * from '../connectors/webtoontr.mjs'
import * from '../connectors/wecomics.mjs'
import * from '../connectors/westmanga.mjs'
import * from '../connectors/whimsubs.mjs'
import * from '../connectors/whitecloudpavilion.mjs'
import * from '../connectors/wiemanga.mjs'
import * from '../connectors/worldthree.mjs'
import * from '../connectors/wowescans.mjs'
import * from '../connectors/wuxiaworld.mjs'
import * from '../connectors/xanimeseduccion.mjs'
import * from '../connectors/yamitenshinofansub.mjs'
import * from '../connectors/yaoichan.mjs'
import * from '../connectors/yaoihavenreborn.mjs'
import * from '../connectors/yaoislife.mjs'
import * from '../connectors/yesmangasbr.mjs'
import * from '../connectors/yokaijump.mjs'
import * from '../connectors/yomanga.mjs'
import * from '../connectors/youbamanga.mjs'
import * from '../connectors/youbamanganext.mjs'
import * from '../connectors/youngaceup.mjs'
import * from '../connectors/yuriism.mjs'
import * from '../connectors/zeroscans.mjs'
import * from '../connectors/zinmanga.mjs'
import * from '../connectors/zmanga.mjs'
*/

export default class Connectors {

    constructor(request) {
        //
        request.registerProtocol( 'connector', this._protocolHandler.bind( this ) );
        
        // raw list of all available connectors
        this.list = [];

        // #region System
        this.register( new BookmarkConnector() );
        this.register( new FolderConnector() );
        // #endregion

this.register( new AnimExtremist() );
/*

        this.register( new ActionManga() );
        this.register( new AnimExtremist() );
        this.register( new Batoto() );
        this.register( new BookLive() );
        this.register( new BoredomSociety() );
        this.register( new Buka() );
        this.register( new ComicEarthStar() );
        this.register( new CiayoEN() );
        this.register( new CiayoID() );
        this.register( new ComicMeteor() );
        this.register( new ComicWalker() );
        this.register( new CrunchyManga() );
        this.register( new DaumWebtoon() );
        this.register( new DigitalTeam() );
        this.register( new DongManManhua() );
        this.register( new DoujinDesu() );
        this.register( new DynastyScans() );
        this.register( new EightMuses() );
        this.register( new ElevenToon() );
        this.register( new GammaPlus() );
        this.register( new GanGanOnline() );
        this.register( new Ganma() );
        this.register( new GetManhwa() );
        this.register( new GManga() );
        this.register( new Gntai() );
        this.register( new GoldenMangas() );
        this.register( new HeavenManga() );
        this.register( new HeavenManga2() );
        this.register( new Hentai2Read() );
        this.register( new HentaiNexus() );
        this.register( new Hitomi() );
        this.register( new HolyManga() );
        this.register( new ItaScan() );
        this.register( new JapanRead() );
        this.register( new JapScan() );
        this.register( new KissAnime() );
        this.register( new KissComic() );
        this.register( new KissManga() );
        this.register( new KoMBatch() );
        this.register( new KuManga() );
        this.register( new LELScan() );
        this.register( new LezhinEN() );
        this.register( new LezhinJA() );
        this.register( new LezhinKO() );
        this.register( new LineWebtoonEN() );
        this.register( new LineWebtoonID() );
        this.register( new LineWebtoonTH() );
        this.register( new LineWebtoonZH() );
        this.register( new MangaArab() );
        this.register( new MangaBat() );
        this.register( new MangaCanBlog() );
        this.register( new MangaChan() );
        this.register( new MangaCross() );
        this.register( new MangaDex() );
        this.register( new MangaDropOutArchive() );
        this.register( new MangaEdenEN() );
        this.register( new MangaEdenIT() );
        this.register( new MangaFox() );
        this.register( new MangaFull() );
        this.register( new MangaGo() );
        this.register( new MangaHasu() );
        this.register( new MangaHere() );
        this.register( new MangaHost() );
        this.register( new MangaIndoWeb() );
        this.register( new MangaInn() );
        this.register( new MangaKakalot() );
        this.register( new MangaLib() );
        this.register( new MangaLife() );
        this.register( new MangaNel() );
        this.register( new MangaPanda() );
        this.register( new MangaPark() );            
        this.register( new MangaParkEN() );
        this.register( new MagaParkPublisher() );
        this.register( new MangaReader() );
        this.register( new MangaRock() );
        this.register( new MangaRussia() );
        this.register( new MangaSail() );
        this.register( new MangaSee() );
        this.register( new MangaStream() );
        this.register( new MangaTail() );
        this.register( new MangaTensei() );
        this.register( new MangaToonCN() );
        this.register( new MangaToonEN() );
        this.register( new MangaToonES() );
        this.register( new MangaToonID() );
        this.register( new MangaToonVI() );
        this.register( new MangaTown() );
        this.register( new MangaTR() );
        this.register( new MangaTube() );
        this.register( new MangaWindow() );
        this.register( new MangaZukiArchive() );
        this.register( new ManhuaBox() );
        this.register( new ManHuaGui() );
        this.register( new ManHuaKan() );
        this.register( new ManhuaTai() );
        this.register( new MerakiScans() );
        this.register( new Mexat() );
        this.register( new MintManga() );
        this.register( new MuchoHentai() );
        this.register( new MyReadingManga() );
        this.register( new Naver() );
        this.register( new NetEaseComic() );
        this.register( new NeuManga() );
        this.register( new Nightow() );
        this.register( new NineAnime() );
        this.register( new NineMangaBR() );
        this.register( new NineMangaDE() );
        this.register( new NineMangaEN() );
        this.register( new NineMangaES() );
        this.register( new NineMangaIT() );
        this.register( new NineMangaRU() );
        this.register( new Ohtabooks() );
        this.register( new RavensScansEN() );
        this.register( new RavensScansES() );
        this.register( new RawSenManga() );
        this.register( new ReadComicBooksOnline() );
        this.register( new ReadManga() );
        this.register( new ReadMNG() );
        this.register( new ReadRawManga() );
        this.register( new ScanManga() );
        this.register( new ScanTrad() );
        this.register( new ScantradUnion() );
        this.register( new SelfManga() );
        this.register( new SleepyPandaScans() );
        this.register( new SmackJeeves() );
        this.register( new SoManga() );
        this.register( new Submanga() );
        this.register( new TAADD() );
        this.register( new Tapas() );
        this.register( new Team1x1() );
        this.register( new TencentComic() );
        this.register( new TenManga() );
        this.register( new TimelessLeaf() );
        this.register( new ToomicsEN() );
        this.register( new ToomicsKO() );
        this.register( new ToomicsSC() );
        this.register( new ToomicsTC() );
        this.register( new TuhaoManhua() );
        this.register( new TuMangaOnline() );
        this.register( new TuMangaOnlineHentai() );
        this.register( new UnionMangas() );
        this.register( new UraSunday() );
        this.register( new ValhallaScans() );
        this.register( new VRVCrunchyroll() );
        this.register( new VRVHiDive() );
        this.register( new VRVRoosterteeth() );
        this.register( new WebComicGamma() );
        this.register( new WebComicsApp() );
        this.register( new WeComics() );
        //this.register( new WebAce() ); // => Subpages: YoungAceUp, YoungAce, ShonenAce, ...
        this.register( new WebNovel() );
        this.register( new WieManga() );
        this.register( new YaoiHavenReborn() );
        this.register( new YesMangasBR() );
        this.register( new YouBaManga() );
        this.register( new YouBaMangaNext() );
        this.register( new YoungAceUp() ); // => Subpage of WebAce with Freebies

        // #region Template: ComiCake
        //         Sample:   https://whimsubs.xyz/r/directory/
        this.register( new ChampionScans() );
        this.register( new LetItGoScans() );
        this.register( new WhimSubs() );
        // #endregion

        // #region Template: RawLH
        //         Sample:   https://manhwascan.com/manga-list.html
        this.register( new HanaScan() );
        this.register( new LHScan() );
        this.register( new LHTranslation() );
        this.register( new MangaWeek() );
        this.register( new Manhwa18() );
        this.register( new Manhwascan() );
        this.register( new RawLH() );
        this.register( new RawQQ() );
        this.register( new RawQV() );
        // #endregion
        
        // #region Template: Genkan
        //         Sample:   https://psychoplay.co/comics
        this.register( new HunlightScans() );
        this.register( new Kaguyadex() );
        this.register( new KomiScans() );
        this.register( new LeviatanScans() );
        this.register( new LeviatanScansES() );
        this.register( new OneShotScans() );
        this.register( new PsychoPlay() );
        // #endregion

        // #region Template: CoreView
        //         Sample:   https://tonarinoyj.jp/episode/10834108156650141204
        this.register( new ComicBorder() );
        this.register( new ComicDays() );
        this.register( new ComicGardo() );
        this.register( new KurageBunch() );
        this.register( new ShonenJumpPlus() );
        // NOTE: ShonenMagazine currently only provides cross-domain links to ShonenMagazinePocket
        //this.register( new ShonenMagazine() );
        this.register( new ShonenMagazinePocket() );
        this.register( new TonariNoYoungJump() );
        // #endregion

        // #region Template: FoolSlide
        //         Sample:   https://jaiminisbox.com/reader/directory/
        this.register( new AjiaNoScantrad() );
        this.register( new AkaiYuhiMun() );
        this.register( new AnataNoMotokare() );
        this.register( new AntisenseScans() );
        this.register( new AtelierDuNoir() );
        this.register( new BunnysScans() );
        this.register( new CanisMajorScans() );
        this.register( new DangolineNoFansub() );
        this.register( new DeathTollScans() );
        this.register( new DokiFansubs() );
        this.register( new EvilFlowers() );
        this.register( new ForgottenScans() );
        this.register( new FujoshiBitches() );
        this.register( new HelveticaScans() );
        this.register( new HoshikuzuuScans() );
        this.register( new HoshiNoFansub() );
        this.register( new HotChocolateScans() );
        this.register( new IlluminatiManga() );
        this.register( new IskultripScans() );
        this.register( new JaiminisBox() );
        this.register( new JokerFansub() );
        this.register( new KireiCake() );
        this.register( new KirishimaFansub() );
        this.register( new Lilyreader() );
        this.register( new LoliVault() );
        this.register( new LupiTeam() );
        this.register( new MangaichiScans() );
        this.register( new MangajinNoFansub() );
        this.register( new MangaScouts() );
        this.register( new MangaSubES() );
        this.register( new Mangatellers() );
        this.register( new MenudoFansub() );
        this.register( new NeoProjectScans() );
        this.register( new NoraNoFansub() );
        this.register( new OneTimeScans() );
        this.register( new PatyScans() );
        this.register( new PCNet() );
        this.register( new PhoenixSerenade() );
        this.register( new PowerManga() );
        this.register( new Pzykosis666HFansub() );
        this.register( new Riceballicious() );
        this.register( new RoseliaScanlations() );
        this.register( new Russification() );
        this.register( new S2Scans() );
        this.register( new SeaOtterScans() );
        this.register( new SeinagiAdultoFansub() );
        this.register( new SeinagiFansubEN() );
        this.register( new SeinagiFansubES() );
        this.register( new SenseScans() );
        this.register( new ShoujoHearts() );
        this.register( new ShoujoSense() );
        this.register( new SilentSkyScans() );
        this.register( new SolitarioNoFansub() );
        this.register( new StormInHeaven() );
        this.register( new TapTrans() );
        this.register( new TheCatScans() );
        this.register( new TrueColorsScan() );
        this.register( new TsubasaSociety() );
        this.register( new TwistedHelScans() );
        this.register( new VortexScans() );
        this.register( new WorldThree() );
        this.register( new XAnimeSeduccion() );
        this.register( new YamiTenshiNoFansub() );
        this.register( new YaoiIsLife() );
        this.register( new YuriISM() );
        // #endregion

        // #region Template: MangaReaderCMS
        //         Sample:   https://manga.fascans.com/manga-list
        this.register( new Biamam() );
        this.register( new FallenAngelsScans() );
        this.register( new HatigarmScans() );
        this.register( new KomikGue() );
        this.register( new Komikid() );
        this.register( new KomikManga() );
        this.register( new KomikZone() );
        this.register( new LELScanVF() );
        this.register( new LeoManga() );
        this.register( new MangaDenizi() );
        this.register( new MangaDoor() );
        this.register( new MangaKawaii() );
        this.register( new MangaLEL() );
        this.register( new MangarawOnline() );
        this.register( new MangAs() );
        this.register( new MangaVadisi() );
        this.register( new MangaZukiRAWS() );
        this.register( new MangaZukiScans() );
        this.register( new OnManga() );
        this.register( new RawMangaSite() );
        this.register( new RawMangaUpdate() );
        this.register( new ReadComicsOnline() );
        this.register( new RenascenceScans() );
        this.register( new ScanFR() );
        this.register( new ScanOP() );
        this.register( new ScanVF() );
        this.register( new SOSScanlation() );
        this.register( new UniversoYuri() );
        this.register( new WhiteCloudPavilion() );
        this.register( new WoweScans() );
        // TODO: add these websites ...
        //Triple("en", "Mangawww Reader", "http://mangawww.club"),
        //Triple("en", "ZXComic", "http://zxcomic.com"),
        //Triple("en", "MangaTreat Scans", "http://www.mangatreat.com"),
        //Triple("pl", "ToraScans", "http://torascans.pl"),
        //Triple("pt", "Comic Space", "https://www.comicspace.com.br"),
        //Triple("pt", "Mangás Yuri", "https://mangasyuri.net"),
        //Triple("pl", "Dracaena", "http://dracaena.webd.pl/czytnik"),
        //Triple("pl", "Nikushima", "http://azbivo.webd.pro"),
        //Triple("ru", "Anigai clan", "http://anigai.ru"),
        //Triple("tr", "MangaHanta", "http://mangahanta.com"),
        //Triple("vi", "Fallen Angels Scans", "http://truyen.fascans.com"),
        //Triple("multi-lingual", "HentaiShark", "https://www.hentaishark.com"))
        // #endregion

        // #region Template: WordPressClarityMangaReader
        //         Sample:   https://www.plot-twistnf-scans.com/proyectos-activos/
        this.register( new PlotTwistNoFansub() );
        // #endregion

        // #region Template: WordPressEManga
        //         Sample:   https://mangashiro.net/daftar-manga/?list
        this.register( new BacaManga() );
        this.register( new KazeManga() );
        this.register( new Kiryuu() );
        this.register( new KomikAV() );
        this.register( new KomikCast() );
        this.register( new KomikIndo() );
        this.register( new KomikIndoWeb() );
        this.register( new KomikMama() );
        this.register( new KomikOtaku() );
        this.register( new KomikStation() );
        this.register( new Komiku() );
        this.register( new Kyuroku() );
        this.register( new MaID() );
        this.register( new Mangaceng() );
        this.register( new Mangaid() );
        this.register( new MangaIndo() );
        this.register( new MangaKid() );
        this.register( new MangaKita() );
        this.register( new MangaPus() );
        this.register( new MangaSeno() );
        this.register( new MangaShiro() );
        this.register( new Ngomik() );
        this.register( new OtakuFile() );
        this.register( new OtakuIndo() );
        this.register( new PecintaKomik() );
        this.register( new WestManga() );
        // #endregion

        // #region Template: WordPressLightPro
        //         Sample:   http://www.authrone.com/manga-list/all/any/name-az/21/
        this.register( new Authrone() );
        this.register( new EyeOnManga() );
        this.register( new Manga99() );
        this.register( new MangaDeep() );
        this.register( new MangaLoverArchive() );
        this.register( new ReadHentaiManga() );
        // #endregion

        // #region Template: WordPressMadara
        //         Sample:   https://mangazuki.me/manga/?m_orderby=alphabet
        this.register( new AllManga() );
        this.register( new AOC() );
        this.register( new AzoraManga() );
        this.register( new ChibiManga() );
        this.register( new CopyPasteScan() );
        this.register( new DarkSkyProjects() );
        this.register( new DoujinYosh() );
        this.register( new FirstKiss() );
        this.register( new GodsRealmScan() );
        this.register( new GrafiManga() );
        this.register( new HappyTeaScans() );
        this.register( new HentaiRead() );
        this.register( new HunterFansub() );
        this.register( new IsekaiRaw() );
        this.register( new IsekaiScan() );
        this.register( new JustForFun() );
        this.register( new Kanjiku() );
        this.register( new KlikManga() );
        this.register( new KnightNoFansub() );
        this.register( new KomikGo() );
        this.register( new LuxyScans() );
        this.register( new MangaDropOut() );
        this.register( new MangaLike() );
        this.register( new MangaLover() );
        this.register( new MangaSushi() );
        this.register( new MangaSY() );
        this.register( new MangaYosh() );
        this.register( new MangaZuki() );
        this.register( new MangaZukiClub() );
        this.register( new MangaZukiInfo() );
        this.register( new MangaZukiOnline() );
        this.register( new MangaZukiSite() );
        this.register( new ManhwaClub() );
        this.register( new ManhwaHand() );
        this.register( new ManhwaHentai() );
        this.register( new ManhwaHentaiMe() );
        this.register( new ManyToon() );
        this.register( new MuchoDoujins() );
        this.register( new NinjaScans() );
        this.register( new PocketAngelScans() );
        this.register( new ReadManhua() );
        this.register( new SiXiangScans() );
        this.register( new Toonily() );
        this.register( new TrashScanlations() );
        this.register( new TritiniaScans() );
        this.register( new TsubakiNoScan() );
        this.register( new WuxiaWorld() );
        this.register( new YokaiJump() );
        this.register( new YoManga() );
        this.register( new ZeroScans() );
        this.register( new ZinManga() );
        this.register( new ZManga() );
        // #endregion

        // #region FMD IMPORT
        this.register( new NineHentai() );
        this.register( new AcademyVN() );
        this.register( new AllHentai() );
        this.register( new AsmHentai() );
        this.register( new BlogTruyen() );
        this.register( new CentralDeMangas() );
        this.register( new ComicExtra() );
        this.register( new Comico() );
        this.register( new ComicoID() );
        this.register( new ComicVN() );
        this.register( new Desu() );
        this.register( new Doujins() );
        this.register( new EGScans() );
        this.register( new EHentai() );
        this.register( new ExHentai() );
        this.register( new FunManga() );
        this.register( new HamTruyen() );
        this.register( new HenChan() );
        this.register( new HentaiCafe() );
        this.register( new HentaiFox() );
        this.register( new HentaiHere() );
        this.register( new HoduComics() );
        this.register( new IMangaScans() );
        this.register( new Imgur() );
        this.register( new InManga() );
        this.register( new KissDoujin() );
        this.register( new Leitor() );
        this.register( new LineWebtoonTranslate() );
        this.register( new Luscious() );
        this.register( new Madokami() );
        this.register( new MangaDoom() );
        this.register( new MangaForAll() );
        this.register( new MangaFoxFun() );
        this.register( new MangaFreak() );
        this.register( new MangaHereFun() );
        this.register( new MangaHispano() );
        this.register( new MangaHome() );
        this.register( new MangaHub() );
        this.register( new MangaHubRU() );
        this.register( new MangaKakalotFun() );
        this.register( new MangaKu() );
        this.register( new MangaOku() );
        this.register( new MangaOnline() );
        this.register( new MangaOnlineBR() );
        this.register( new MangaReaderSite() );
        this.register( new MangaRoom() );
        this.register( new MangaShow() );
        this.register( new NetTruyen() );
        this.register( new NewType() );
        this.register( new NHentai() );
        this.register( new Niadd() );
        this.register( new PervEden() );
        this.register( new PervEdenIT() );
        this.register( new PornComix() );
        this.register( new Pururin() );
        this.register( new Puzzmos() );
        this.register( new ReadMangaEU() );
        this.register( new SenManga() );
        this.register( new Shakai() );
        this.register( new Shogakukan() );
        this.register( new SiberOwl() );
        this.register( new SKSubs() );
        this.register( new SundayWebry() );
        this.register( new Toonkor() );
        this.register( new TruyenChon() );
        this.register( new TruyenTranhtuan() );
        this.register( new Tsumino() );
        this.register( new TurkCraft() );
        this.register( new VNSharing() );
        this.register( new WebtoonTR() );
        this.register( new YaoiChan() );
        // #endregion
*/
    }

    register( connector ) {
        // determine if connector is already registered
        if( this.list.find( c => c.id === connector.id ) ) {
            return;
        }
        this.list.push( connector );
        this.list.sort( ( a, b ) => {
            return ( a.label.toLowerCase() < b.label.toLowerCase() ? -1 : 1 );
        } );
    }
    
    _protocolHandler( request, callback ) {
        let uri = new URL( request.url );
        this.list.find( connector => connector.id === uri.hostname ).handleConnectorURI( uri )
        .then( buffer => callback( buffer ) )
        .catch( error => {
            //console.error( error, payload );
            callback( undefined );
        } );
    }
}